title: anikeshk's Notes
description: Notes on masters, interview preparation and other ramblings by Anikesh G Kamath
theme: just-the-docs

url: https://anikeshk.github.io/notes/

aux_links:
  anikeshk.com: https://anikeshk.com/
